rootProject.name = 'ecommerce-medical-platform'

// (optional) nice DX for referencing subprojects as code
enableFeaturePreview('TYPESAFE_PROJECT_ACCESSORS')

include(
        'platform',
        ':services:catalog-service',
        ':services:order-service',
        ':services:payment-service',
        ':services:inventory-service',
        ':clients:admin-ui',
        ':clients:shop-ui'
)

project(":platform").buildFileName = "build.gradle"
include 'starters'
include 'starters:ecom-security-starter'
include 'starters:ecom-kafka-starter'
include 'starters:ecom-web-starter'
include 'starters:ecom-mongo-starter'