apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: root
  MONGO_ROOT_PASSWORD: password
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  STRIPE_SECRET_KEY: "sk_test_12345"
