ecom:
  redis:
    enabled: true
    host: redis
    port: 6379
    ttl-seconds: 300
    key-prefix: payment-service
  security:
    enabled: true
    jwt:
      hmac-secret: ${JWT_SECRET:dev-secret}
  kafka:
    enabled: true
    auto-create-topics: true
    product-topic: catalog.product.v1
    order-topic: orders.order.v1
    payment-topic: payments.payment.v1
    stock-topic: inventory.stock.v1

# Stripe config (test mode)
stripe:
  api-key: ${STRIPE_API_KEY:}                 # sk_test_xxx
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}   # from stripe cli forward

spring:
  application.name: payment-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:password@mongo-payment:27017/payments?authSource=admin}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.data.mongodb: INFO
    com.github.ku4marez: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name:payment-service}
