apiVersion: v2
name: payment-service
description: Helm chart for Payment Service microservice
type: application
version: 0.1.0     # Chart version
appVersion: "1.0"  # App version (can match Docker tag)
