apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}- ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "dev.local"
      http:
        paths:
          - path: /catalog
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}
