replicaCount: 1

image:
  repository: ku4marez/myrepo
  tag: inventory-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  path: /inventory

resources: {}

env:
  SPRING_PROFILES_ACTIVE: k8s
