name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

#      - uses: gradle/actions/setup-gradle@v4

      - name: Set up GitHub Packages credentials
        run: |
          echo "GPR_USER=${{ secrets.GPR_USER  }}" >> $GITHUB_ENV
          echo "GPR_TOKEN=${{ secrets.GPR_TOKEN }}" >> $GITHUB_ENV

      - name: Build everything
        run: ./gradlew --no-daemon --stacktrace clean build -x test
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push catalog-service
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/catalog-service:${{ github.sha }}"
          docker build -t "$IMAGE" -f ./services/catalog-service/Dockerfile --build-arg GPR_USER=${{ secrets.GPR_USER }} --build-arg GPR_TOKEN=${{ secrets.GPR_TOKEN }} .
          docker push "$IMAGE"
        if: always()

      - name: Build & push order-service
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/order-service:${{ github.sha }}"
          docker build -t "$IMAGE" -f ./services/order-service/Dockerfile .
          docker push "$IMAGE"
        if: always()

      - name: Build & push gateway-service
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/gateway-service:${{ github.sha }}"
          docker build -t "$IMAGE" -f ./services/gateway-service/Dockerfile .
          docker push "$IMAGE"
        if: always()

      - name: Build & push inventory-service
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/inventory-service:${{ github.sha }}"
          docker build -t "$IMAGE" -f ./services/inventory-service/Dockerfile .
          docker push "$IMAGE"
        if: always()

      - name: Build & push payment-service
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/payment-service:${{ github.sha }}"
          docker build -t "$IMAGE" -f ./services/payment-service/Dockerfile .
          docker push "$IMAGE"
        if: always()

      - name: Save image tags for deploy step
        run: |
          echo "CATALOG_IMAGE=ghcr.io/${{ github.repository_owner }}/catalog-service:${{ github.sha }}" >> image-tags.txt
          echo "ORDER_IMAGE=ghcr.io/${{ github.repository_owner }}/order-service:${{ github.sha }}" >> image-tags.txt
          echo "GATEWAY_IMAGE=ghcr.io/${{ github.repository_owner }}/gateway-service:${{ github.sha }}" >> image-tags.txt
          echo "INVENTORY_IMAGE=ghcr.io/${{ github.repository_owner }}/inventory-service:${{ github.sha }}" >> image-tags.txt
          echo "PAYMENT_IMAGE=ghcr.io/${{ github.repository_owner }}/payment-service:${{ github.sha }}" >> image-tags.txt
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: image-tags
          path: image-tags.txt

#      - name: Upload catalog-service JAR
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: catalog-service-jar
#          path: services/catalog-service/build/libs/*.jar
#
#      - name: Upload inventory-service JAR
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: inventory-service-jar
#          path: services/inventory-service/build/libs/*.jar
#
#      - name: Upload order-service JAR
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: order-service-jar
#          path: services/order-service/build/libs/*.jar
#
#      - name: Upload payment-service JAR
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: payment-service-jar
#          path: services/payment-service/build/libs/*.jar
