plugins {
    id 'java-library'
}

dependencies {
    api platform(project(":platform"))

    api 'org.springframework.boot:spring-boot-autoconfigure'

    api "org.springframework.boot:spring-boot-starter-data-redis"
    api "org.springframework.boot:spring-boot-starter-cache"
    api "com.fasterxml.jackson.core:jackson-databind"
    api "org.springframework.data:spring-data-redis"
}

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
